//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHomeWork.Areas.HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string BankName { get; set; }
        public int BankNo { get; set; }
        public Nullable<int> SubBankNo { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
