//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHomeWork.Areas.HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigCode
    {
        public int CodeKey { get; set; }
        public string CodeType { get; set; }
        public string CodeName { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
