//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHomeWork.Areas.HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersList
    {
        public int Id { get; set; }
        public string CompanyNo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BankCount { get; set; }
        public Nullable<int> ContactCount { get; set; }
    }
}
